---
- hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: False
    - ansible_stdout_callback: yaml
  roles:
    - configs
